# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISCSM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='Link_Monitor',
            field=models.URLField(blank=True, null=True),
        ),
    ]
