# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISCSM', '0002_serverinfo_link_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='DestinationIP',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='SourceIP',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='Way',
            field=models.CharField(choices=[('in', 'IN'), ('out', 'OUT'), ('2 way', '2 WAY')], default='in', max_length=5),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='OS',
            field=models.CharField(choices=[('wds', 'Windows'), ('lns', 'Linux'), ('exi', 'ESxi')], default='lns', max_length=3),
        ),
    ]
