# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISCSM', '0003_auto_20160831_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='Port',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
