# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISCSM', '0004_auto_20160831_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='ZoneName',
            field=models.CharField(max_length=60),
        ),
    ]
