# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISCSM', '0007_auto_20161116_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='Function',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='OS_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='ServerType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
