# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-12 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISCSM', '0010_firewall_datecreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='DateCreate',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
