# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-13 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISCSM', '0011_service_datecreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
