# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-19 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISCSM', '0012_service_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to=b'')),
                ('delete_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to=b'')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='Description',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
    ]
