# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-20 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISCSM', '0013_auto_20170719_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='DestinationIP',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='SourceIP',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
