# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-20 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISCSM', '0015_auto_20170720_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='SourceIP',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
