# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-20 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISCSM', '0016_auto_20170720_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='SourceIP',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
