# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-03 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.CharField(default=b'', max_length=50)),
                ('dest_ip', models.CharField(default=b'', max_length=4000)),
                ('port', models.CharField(default=b'', max_length=4000)),
                ('description', models.CharField(default=b'', max_length=4000)),
                ('datecreate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationName', models.CharField(blank=True, max_length=50, null=True)),
                ('Rack', models.CharField(blank=True, max_length=50, null=True)),
                ('Unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerName', models.CharField(blank=True, max_length=50, null=True)),
                ('IP', models.GenericIPAddressField(protocol=b'IPv4', unique=True)),
                ('OS', models.CharField(choices=[(b'wds', b'Windows'), (b'lns', b'Linux'), (b'exi', b'ESxi')], default=b'lns', max_length=3)),
                ('OS_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Function', models.CharField(blank=True, max_length=200, null=True)),
                ('ServerType', models.CharField(blank=True, max_length=200, null=True)),
                ('CPU', models.CharField(blank=True, max_length=500, null=True)),
                ('RAM', models.CharField(blank=True, max_length=200, null=True)),
                ('HDD', models.CharField(blank=True, max_length=500, null=True)),
                ('Link_Monitor', models.URLField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(blank=True, max_length=50, null=True)),
                ('ServiceType', models.CharField(choices=[(b'win', b'win'), (b'web', b'web'), (b'db', b'db')], default=b'win', max_length=5)),
                ('URL', models.URLField(blank=True, null=True)),
                ('RunningAs', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.TextField(blank=True, max_length=900, null=True)),
                ('URLWEBS', models.URLField(blank=True, null=True)),
                ('Header', models.TextField(blank=True, max_length=800, null=True)),
                ('Body', models.TextField(blank=True, max_length=1000, null=True)),
                ('DateCreate', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('Owner', models.CharField(blank=True, max_length=50, null=True)),
                ('Server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISCSM.ServerInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SwitchIP', models.GenericIPAddressField(blank=True, null=True, protocol=b'IPv4')),
                ('SwitchType', models.CharField(choices=[(b'cso', b'Cisco'), (b'dtk', b'DrayTek')], default=b'dtk', max_length=5)),
                ('SwitchPort', models.CharField(blank=True, max_length=10, null=True)),
                ('SwitchLocation', models.CharField(blank=True, max_length=10, null=True)),
                ('Server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISCSM.ServerInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=b'', max_length=4000)),
                ('start_date', models.CharField(default=b'', max_length=50)),
                ('due_date', models.CharField(default=b'', max_length=50)),
                ('done', models.CharField(default=b'', max_length=50)),
                ('status', models.CharField(default=b'', max_length=50)),
                ('assignee', models.CharField(default=b'', max_length=50)),
                ('department', models.CharField(default=b'', max_length=50)),
                ('tracker', models.CharField(default=b'', max_length=50)),
                ('complexity', models.CharField(default=b'', max_length=50)),
                ('estimated_time', models.CharField(default=b'', max_length=50)),
                ('spent_time', models.CharField(default=b'', max_length=50)),
                ('actual_end_date', models.CharField(default=b'', max_length=50)),
                ('project', models.CharField(default=b'', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
                ('filename', models.CharField(default=b'', max_length=50)),
                ('category', models.CharField(default=b'', max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(blank=True, max_length=50)),
                ('del_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=50)),
                ('path', models.CharField(default=b'', max_length=200)),
                ('title', models.CharField(default=b'', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WebService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default=b'', max_length=50, unique=True)),
                ('service', models.CharField(default=b'', max_length=50, unique=True)),
                ('server', models.CharField(default=b'', max_length=4000)),
                ('description', models.CharField(default=b'', max_length=200)),
                ('ha', models.CharField(default=b'', max_length=200)),
                ('path', models.CharField(default=b'', max_length=4000)),
                ('author', models.CharField(default=b'', max_length=50)),
                ('state', models.CharField(default=b'', max_length=4000)),
                ('protocol', models.CharField(default=b'', max_length=4000)),
                ('ip_restrict', models.CharField(default=b'', max_length=100)),
                ('del_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WinService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default=b'', max_length=50, unique=True)),
                ('server', models.CharField(default=b'', max_length=4000)),
                ('description', models.CharField(default=b'', max_length=200)),
                ('author', models.CharField(default=b'', max_length=4000)),
                ('state', models.CharField(default=b'', max_length=4000)),
                ('del_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZoneName', models.CharField(max_length=60)),
                ('Description', models.TextField(blank=True, max_length=300, null=True)),
                ('Network', models.GenericIPAddressField(blank=True, default=None, null=True, protocol=b'IPv4', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='ZoneName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISCSM.Zone'),
        ),
        migrations.AddField(
            model_name='location',
            name='Server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISCSM.ServerInfo'),
        ),
    ]
